apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: dn2byqv5n-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-62ae6469fb.rwkj.p3.openshiftapps.com/rhtap/rhtap-qe:a2f554f852b066e7bd94f47447131bbabf9ef80d@sha256:980ece564d766f11d208d36a94de12dc07ff60a579a4ebf543adc6a0574e3ef9
          name: container-image
